@startuml

class Client{
}

class Receiver{
    action()
}

interface Command{
    execute()
    undo()
}

class ConcreteCommand{
    execute()
    undo()
}

class Invoker{

}

Receiver <- Client
Client -> ConcreteCommand
Receiver <-- ConcreteCommand

Command <|.. ConcreteCommand

Command <- Invoker




@enduml